### ISSUE TITLE
Lỗi khi dùng go get

### ISSUE THREAD

**Issue by reallongnguyen** [philipdac/num2vn-go#1]
$go get github.com/philipdac/num2vn-go.git
package github.com/philipdac/num2vn-go.git: invalid version control suffix in github.com/ path

**Comment by philipdac** [comment]
I tried "go get github.com/philipdac/num2vn-go" (without .git) under Ubuntu 14.04 and it worked.

**Comment by reallongnguyen** [comment]
Cảm ơn. Mình đã nhầm lẫn khi dùng go get.
